# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18eee12981339faa870297cb70c5f097198297957892937030e9758242e37648d9db68e92e074eccaf1774021cc97b91aaf325cd8f6edd430958ba208d15ce27

test:
  secret_key_base: 236f43dd3f6f9a796b9d3c5aab3397e9a9c0761641b308259362a127c987f84a84c8751ed004f77898b23f028b799becea7d0d220eed77e7f43052e4c5aa050a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
